- docs/ProblemStatementAndGoals/ProblemStatement.tex
20/09/23
Digested our problem statement into the doc.
- added to tex file
> Issue#15: Added 1.1 problem statement to doc

- docs/DevelopmentPlan/DevelopmentPlan.tex
20/09/23
Added Team Meeting Plan in Dev Plan doc
- Development Plan document
> Issue #10: Completed Team Meeting Plan section of Development Plan Document

- docs/DevelopmentPlan/DevelopmentPlan.tex
- docs/ProblemStatementAndGoals/ProblemStatement.tex
20/09/23
Added Inputs and Outputs in Problem Statement and Goals document.
- Problem Statement and Goals document
- Added new Inputs and Outputs
> Issue #11: Completed Input and Output section in Problem Statement and Goals document

- docs/ProblemStatementAndGoals/ProblemStatement.tex
23/09/23
{issue description}
- Software Environment
- Hardware Environment
> Issue #27: Environment

- docs/ProblemStatementAndGoals/ProblemStatement.tex
23/09/23
Wrote some goals and stretch goals based on discussion from meetings
- Problem Statement Goals and Stretch Goals
- We may need to discuss these further as a group later. At least for me, I had the wrong idea about Stretch Goals. Essentially, if we write a Stretch Goal, it is with the intention of adding it to the project and we should discuss with everyone if we're gonna for sure commit to developing these.
> Issue #37: Create initial goals and stretch goals for the project

- docs/DevelopmentPlan/DevelopmentPlan.tex
24/09/23
Added coding standards section to docs
- added details on coding standards
- added details on linters
-
> Issue #42: Define Coding standards for Dev Plan

- docs/DevelopmentPlan/DevelopmentPlan.tex
- docs/ProblemStatementAndGoals/ProblemStatement.tex
--/--/--
Completed Stakeholders section of Problem Statement and Goals document.
- Stakeholders
- Revision Midrule
> Issue #26: Stakeholders Completed

- docs/DevelopmentPlan/DevelopmentPlan.tex
24/09/23
Completed a draft of the Technology
- Technology
> Issue #44: technology

- docs/DevelopmentPlan/DevelopmentPlan.tex
24/09/23
Completed a draft of the Proof of Concept Demonstration Plan
- Proof of Concept Demonstration Plan
> Issue #43: Wrote proof of concept demonstration plan

- docs/ProblemStatementAndGoals/ProblemStatement.tex
--/--/--
Removed team members from Stakeholders section in Problem Statement and Goals Document.
- Stakeholders
> Issue #50: Fix stakeholders

- docs/SRS-Volere/SRS.tex
28/09/23
Adds an initial version of Section 1 on the SRS Document
- Purpose of the Project
> Issue #60: Added Section 1 to SRS Document

- docs/SRS-Volere/SRS.tex
30/09/23
Adds initial Look and Feel requirements as well as an added appendix section with notes from stakeholder elicitation.
- Look and Feel Requirements
- Appendix
> Issue #61: Adds Look and Feel Requirements for SRS

- docs/SRS-Volere/SRS.tex
30/09/23
Adds an initial version of the Usability and Humanity Requirements based on elicitation
- Usability and Humanity Requirements
> Issue #62: Added Usability and Humanity Requirements

- docs/SRS-Volere/SRS.tex
30/09/23
Adds an initial version of the Performance Requirements to the SRS
- Performance Requirements
> Issue #63: Adds Performance Requirements

- docs/SRS-Volere/SRS.tex
03/10/23
added stakeholder section
> Issue #54: Section 2 - SRS Stakeholders

- docs/SRS-Volere/SRS.tex
04/10/23
Adds an answer to Question 1 of the Reflection as well as preamble to everyone's responses in Question 2. I also added sections for each of us below the Question 2 preamble to put our reflection responses. This also includes my own reflection as part of the PR.
- Appendix: Reflection
- Remember when you're doing your own reflection, that when writing your approach to learning/mastering the chosen skills, that the expectation is to choose from the approaches in the preamble. I tried to create as in-depth options as I could.
> Issue #101: Reflection Premable, Template and Personal Reflection

- docs/SRS-Volere/SRS.tex
01/10/-23
added off the shelf solutions to SRS
> Issue #85: SRS - Off the Shelf solutions 

- docs/SRS-Volere/SRS.tex
> Issue #86 : SRS - Migration

- docs/SRS-Volere/SRS.tex
01/10/23
Added Maintainability and Support Reqs
- Added Maintainability and Support Reqs
> Issue #58 : SRS - Maintainability and Support Req

- docs/SRS-Volere/SRS.tex
https://github.com/r-yeh/grocery-spending-tracker/issues/66
> Issue #66: Cultural NFRs

- docs/SRS-Volere/SRS.tex
https://github.com/r-yeh/grocery-spending-tracker/issues/95
Add more if you have any thanks
>  Issue #95: Ideas for solutions

- docs/SRS-Volere/SRS.tex
01/10/23
Relevant Facts and Assumptions
- Relevant Facts
- Assumptions
- Business Rules (?)
- Not sure what to add to Business Rules sections.
> Issue #69: Added Relevant Facts and Assumptions

- docs/SRS-Volere/SRS.tex
01/10/23
Operational and Environmental Requirements section from SRS document.
- Operational and Environmental Requirements
> Issue #71: Operational and Environmental NFR

- docs/SRS-Volere/SRS.tex
01/10/23
Security NFR section of SRS document
- Security Requirements
> Issue #72: Added Security NFR

- docs/SRS-Volere/SRS.tex
--/--/--
New Problems section completed in SRS.tex document.
- New Problems
> Issue #110: Added New Problems

- docs/SRS-Volere/SRS.tex
05/10/23
Added User Documentation and Training section in SRS Document
- User Documentation and Training
> Issue #111: Added User Documentation and Training

- docs/SRS-Volere/SRS.tex
05/10/23
Wrote reflection for appendix
> #104: Write Personal Reflection

- docs/SRS-Volere/SRS.tex
[Do not merge, just add your terms]
(https://github.com/r-yeh/grocery-spending-tracker/issues/56)
> Issue #56: Terms to SRS Document

- docs/SRS-Volere/SRS.tex
https://github.com/r-yeh/grocery-spending-tracker/issues/102
> Issue #102:Reflection

- docs/HazardAnalysis/HazardAnalysis.tex
https://github.com/r-yeh/grocery-spending-tracker/issues/136
> Issue #136: HA system boundaries

- docs/ProblemStatementAndGoals/ProblemStatement.tex
17/10/23
Added metrics to some goals and reordered them according to the rubric feedback
- Problem Statement Goals
> Updated Problem Statement goals based on feedback from TA

- docs/HazardAnalysis/HazardAnalysis.tex
https://github.com/r-yeh/grocery-spending-tracker/issues/134
> 134: HA Introduction

- docs/HazardAnalysis/HazardAnalysis.tex
https://github.com/r-yeh/grocery-spending-tracker/issues/135
> 135: HA scope/purpose

- .gitmodules
This reverts commit 61f3cbafa01abd246ff78619d8e74f9deb7d5bb9.
> Revert "added submodules (#148)"

- docs/HazardAnalysis/HazardAnalysis.tex
16/10/23
Wrote out an initial version of the Failure and Effect Analysis Table. Due to the difficulty of reading the code itself, below are the screenshots of the table (**note SR was changed to SSR for IDs since SR is already used in the SRS**):
Also added the List of Tables and List of Figures which was required. The Critical Assumptions was also included in this PR because it was simply one sentence.
- Failure and Effect Analysis Table
- List of Tables
- List of Figures
- Critical Assumptions
> Issue #133 and #137: Failure Effect Analysis Table and Critical Assumptions

- docs/HazardAnalysis/HazardAnalysis.tex
19/10/23
Adds initial iteration for the roadmap of the Hazard Analysis document.
- Roadmap
> Issue #138: Roadmap

- docs/SRS/SRS.tex
26/10/23
Revised FRs based on feedback.
- Functional Requirements section from SRS
> Issue #167: SRS Feedback - FR Revised

- docs/VnVPlan/VnVPlan.tex
01/11/23
Adds the preamble for questions 1 and 2 in addition to my personal reflection. Like the SRS, sections were added for all toehr team members.
> Issue #187: Reflection Preamble and Personal Reflection

- docs/VnVPlan/VnVPlan.tex
2/11/23
Adds System Tests for Security Requirements NFRs
- Section 4.2
- NFRT-SR1 traces back to ACR1
- NFRT-SR2 traces back to INR1
- NFRT-SR3 traces back to INR2
- NFRT-SR4 traces back to PRR1
- NFRT-SR5 traces back to PRR2
- NFRT-SR6 traces back to AUR1
> Issue #177: VnV Section 4.2 Security Requirements NFR Tests

- docs/VnVPlan/VnVPlan.tex
> Issue #194: VnV Reflection Sawyer

- docs/VnVPlan/VnVPlan.tex
> Issue #197: VnV Reflection Jason

- docs/VnVPlan/VnVPlan.tex
2/11/23
Adds Traceability Matrix for all system requirements and tests. FRs are placed on one big table and each NFR is split into their own tables.
- Section 4.3
> Issue #189: System Test Traceability Matrix

- .gitmodules
- refs/submodules.md
Added:
- https://github.com/jason-nam/receipt-data-extractor
- https://github.com/jason-nam/receipt-data-parser
> Issue #148: add submodules

- docs/HazardAnalysis/HazardAnalysis.tex
> Issue #154: New Security Requirement (Strong Password)

- docs/VnVPlan/VnVPlan.tex
> Issue #204: Discrepancy Between FRT-FR2-6 and FRT-FR2-7 

- docs/SRS/SRS.tex
29/11/23
Adds some statistics to the Purpose of Project section as per the feedback.
- Section 1
> Issue #171: Added statistics and citations to Introduction/Purpose of Project

- docs/SRS/SRS.tex
01/12/23
Adds reference headers to each individual use case to show which PUC it is representative of.
- Section 8.3
> Issue #168: Added IDs to PUC References in 8.3

- .gitmodules
https://github.com/r-yeh/grocery-spending-tracker/issues/245
> Issue 245: Add App Submodule

- docs/Design/SoftArchitecture/MG.tex
https://github.com/r-yeh/grocery-spending-tracker/issues/243
> Issue 243: MG Section 7 analytics & location modules

- docs/Design/SoftArchitecture/MG.tex
> Issue #240: MG - Section 5: Module Hierarchy

- docs/Design/SoftArchitecture/MG.tex
10/01/24
Issue #267: MG Section 7 - Users Module, Authentication Module, Database Driver Module
added desc to MG7
- Users Module
- Authentication Module
- DB Module
> Issue #267: MG Section 7 - Users Module, Authentication Module, Database Driver Module

- docs/Design/SoftDetailedDes/MIS.tex
https://github.com/r-yeh/grocery-spending-tracker/issues/272
> Issues 272: add location module to MIS

- docs/Design/SoftDetailedDes/MIS.tex
> Issue #283: MIS Authentication Module

- docs/Design/SoftDetailedDes/MIS.tex
> 282: added MIS: Users

- docs/Design/SoftDetailedDes/MIS.tex
https://github.com/r-yeh/grocery-spending-tracker/issues/274
> Issue 274: MIS for db module

- docs/SRS/SRS.tex
> Issue #252: Revise SRS Functional Requirements Section (FR7, FR12)

- docs/Design/SoftDetailedDes/MIS.tex
https://github.com/r-yeh/grocery-spending-tracker/issues/273
Imma be honest I think I have issues... esp with the Item type I'm using, pls review ty
> Issue 273: MIS analytics module 

- docs/Design/SoftDetailedDes/MIS.tex
> Issue #279: MIS Recommendation Module

- docs/Design/SoftDetailedDes/MIS.tex
> Issue #280: MIS Classification Module

- docs/Design/SoftDetailedDes/MIS.tex
https://github.com/r-yeh/grocery-spending-tracker/issues/295
> Issue 295: Add Purchase History to Analytics Module MIS 

- docs/VnVPlan/VnVPlan.tex
- docs/VnVReport/VnVReport.tex
3/3/2024
Adds the Unit Testing Scope section to the VnV Plan and the Unit Tests for the Extraction module. Also adds the VnV Report Intro and Automated Testing sections.
- VnV Plan Scope
- VnV Plan Unit Tests for Extraction module
- VnV Report Intro
- VnV Report Automated Testing
- Boilerplate stuff for unit testing in VnV Plan and VnV Report
> Issue #360 & #364: VnVPlan Receipt Extraction and VnV Report Intro/Automated Testing

- docs/VnVReport/VnVReport.tex
4/3/2024
Adds the Receipt Extraction portion of the Unit Testing to the VnV Report
- VnV Unit Testing: Receipt Extraction Module
Based off of the information I gathered from our meeting with Chris:
> Issue #369: VnV Report Unit Testing Summary for Receipt Extraction

- docs/SRS/SRS.tex
https://github.com/r-yeh/grocery-spending-tracker/issues/371
> 371/VnV report SRS changes

- docs/VnVPlan/VnVPlan.tex
https://github.com/r-yeh/grocery-spending-tracker/issues/378
> Allan's 5.2 (Auth + user anal)

- docs/VnVPlan/VnVPlan.tex
https://github.com/r-yeh/grocery-spending-tracker/issues/378
> 5.2 : users, auth, analytics

- docs/VnVPlan/VnVPlan.tex
- docs/VnVReport/VnVReport.tex
FRT-FR1-2, FRT-FR3-1, FRT-FR8-2 require user feedback/numbers @r-yeh 
https://github.com/r-yeh/grocery-spending-tracker/issues/379
> VnVReport Frs and associated vnvplan changes

- docs/VnVReport/VnVReport.tex
> Issue #380: VnVReport section 5 unit tests

- docs/VnVPlan/VnVPlan.tex
https://github.com/r-yeh/grocery-spending-tracker/issues/444
details here ^
> Update vnv plan according to avenue feedback

- docs/VnVReport/VnVReport.tex
https://github.com/r-yeh/grocery-spending-tracker/issues/445
> Updated vnv report for avenue feedback
